### ISSUE TITLE
Crash in PetManager

### ISSUE THREAD

**Issue by mindphluxnet** [The-Alpha-Project/alpha-core#1018]
**Describe the bug**

Happened while just running through the Barrens, loc:

![image](https://user-images.githubusercontent.com/4683319/227039726-61579b7a-0539-4572-99ba-260f2888732c.png)

```
Job "WorldSessionStateHandler.update_known_players_objects (trigger: interval[0:00:00.500000], next run at: 2023-03-22 22:10:34 CET)" raised an exception
Traceback (most recent call last):
  File "C:\Users\xbox\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "C:\Users\xbox\source\repos\alpha-core\game\world\WorldSessionStateHandler.py", line 106, in update_known_players_objects
    session.player_mgr.update_known_world_objects()
  File "C:\Users\xbox\source\repos\alpha-core\game\world\managers\objects\units\player\PlayerManager.py", line 423, in update_known_world_objects
    self._update_known_creature(creature, active_objects)
  File "C:\Users\xbox\source\repos\alpha-core\game\world\managers\objects\units\player\PlayerManager.py", line 498, in _update_known_creature
    self.enqueue_packet(creature.generate_create_packet(requester=self))
  File "C:\Users\xbox\source\repos\alpha-core\game\world\managers\objects\ObjectManager.py", line 98, in generate_create_packet
    self.get_object_create_bytes(requester)))
  File "C:\Users\xbox\source\repos\alpha-core\game\world\managers\objects\ObjectManager.py", line 117, in get_object_create_bytes
    self.initialize_field_values()
  File "C:\Users\xbox\source\repos\alpha-core\game\world\managers\objects\units\creature\CreatureManager.py", line 216, in initialize_field_values
    self.object_ai.just_respawned()
  File "C:\Users\xbox\source\repos\alpha-core\game\world\managers\objects\ai\BasicCreatureAI.py", line 50, in just_respawned
    super().just_respawned()
  File "C:\Users\xbox\source\repos\alpha-core\game\world\managers\objects\ai\CreatureAI.py", line 159, in just_respawned
    self.creature.spell_manager.start_spell_cast(initialized_spell=spell)
  File "C:\Users\xbox\source\repos\alpha-core\game\world\managers\objects\spell\SpellManager.py", line 315, in start_spell_cast
    self.perform_spell_cast(casting_spell, validate=False)
  File "C:\Users\xbox\source\repos\alpha-core\game\world\managers\objects\spell\SpellManager.py", line 365, in perform_spell_cast
    self.apply_spell_effects(casting_spell)  # Apply effects
  File "C:\Users\xbox\source\repos\alpha-core\game\world\managers\objects\spell\SpellManager.py", line 424, in apply_spell_effects
    SpellEffectHandler.apply_effect(casting_spell, effect, casting_spell.spell_caster, target)
  File "C:\Users\xbox\source\repos\alpha-core\game\world\managers\objects\spell\SpellEffectHandler.py", line 46, in apply_effect
    SPELL_EFFECTS[effect.effect_type](casting_spell, effect, caster, target)
  File "C:\Users\xbox\source\repos\alpha-core\game\world\managers\objects\spell\SpellEffectHandler.py", line 601, in handle_summon_pet
    caster.pet_manager.summon_permanent_pet(casting_spell.spell_entry.ID, effect.misc_value)
  File "C:\Users\xbox\source\repos\alpha-core\game\world\managers\objects\units\pet\PetManager.py", line 152, in summon_permanent_pet
    active_pet = self.set_creature_as_pet(creature_manager, spell_id, PetSlot.PET_SLOT_PERMANENT,
  File "C:\Users\xbox\source\repos\alpha-core\game\world\managers\objects\units\pet\PetManager.py", line 62, in set_creature_as_pet
    self._handle_creature_spawn_detach(creature, is_permanent)
  File "C:\Users\xbox\source\repos\alpha-core\game\world\managers\objects\units\pet\PetManager.py", line 369, in _handle_creature_spawn_detach
    if creature.get_type_id() != ObjectTypeIds.ID_UNIT or not creature.spawn_id:
AttributeError: 'NoneType' object has no attribute 'get_type_id'
```

**Comment by Fluglow** [comment]
I'm guessing this is caused by us missing a creature entry for Savannah Cub (4227).
```
> select id, name_enus spell, effectmiscvalue_1 creature_entry, name creature from spell left join alpha_world.creature_template ct on ct.entry = effectmiscvalue_1 where effectmiscvalue_1 != 0 and effect_1 in (0x38, 0x1c) and name is NULL;
+------+--------------+----------------+----------+
| id   | spell        | creature_entry | creature |
+------+--------------+----------------+----------+
| 6598 | Savannah Cub |           4227 | NULL     |
+------+--------------+----------------+----------
> select entry, name from creature_template where spell_id1 = 6598;
+-------+--------------------+
| entry | name               |
+-------+--------------------+
|  3416 | Savannah Matriarch |
+-------+--------------------+

**Comment by mindphluxnet** [comment]
Savannah Cub is 5766 in our database. No clue where 4227 comes from ...

**Comment by Fluglow** [comment]
The ID was already changed to 5766 in 0.5.5. Since the DBC is original game data, we should instead assume the correct entry in this version is indeed 4227. One solution would be to copy the existing entry to the old ID.

There's also a related passive spell for Savannah Cub that was removed in 0.5.5. I'd suggest adding this passive for the creature if the behavior is reasonable. It gives a movement and attack speed buff to the controller when the Cub is attacked.
```
+------+----------------------+----------+
| id   | name_enus            | effect_1 |
+------+----------------------+----------+
| 6597 | Savannah Cub Effect  |        6 |
| 6598 | Savannah Cub         |       56 |
| 6599 | Savannah Cub Passive |        6 |
+------+----------------------+----------+
