### ISSUE TITLE
TypeError: 'type' object is not subscriptable when try to run

### ISSUE THREAD

**Issue by Nymphelocke** [The-Alpha-Project/alpha-core#121]
Hi. Tryin to run server but get that error:

(venv) C:\Users\IGOR FEDOROV\PycharmProjects\alpha-core>python main.py
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    from game.world import WorldManager
  File "C:\Users\IGOR FEDOROV\PycharmProjects\alpha-core\game\world\WorldManager.py", line 9, in <module>
    from game.world.WorldLoader import WorldLoader
  File "C:\Users\IGOR FEDOROV\PycharmProjects\alpha-core\game\world\WorldLoader.py", line 6, in <module>
    from game.world.managers.objects.creature.CreatureManager import CreatureManager
  File "C:\Users\IGOR FEDOROV\PycharmProjects\alpha-core\game\world\managers\objects\creature\CreatureManager.py", line 9, in <module>
    from game.world.managers.objects.UnitManager import UnitManager
  File "C:\Users\IGOR FEDOROV\PycharmProjects\alpha-core\game\world\managers\objects\UnitManager.py", line 10, in <module>
    from game.world.managers.objects.spell.AuraManager import AuraManager
  File "C:\Users\IGOR FEDOROV\PycharmProjects\alpha-core\game\world\managers\objects\spell\AuraManager.py", line 4, in <module>
    from game.world.managers.objects.spell.AppliedAura import AppliedAura
  File "C:\Users\IGOR FEDOROV\PycharmProjects\alpha-core\game\world\managers\objects\spell\AppliedAura.py", line 89, in <module>
    class AuraManager:
  File "C:\Users\IGOR FEDOROV\PycharmProjects\alpha-core\game\world\managers\objects\spell\AppliedAura.py", line 162, in AuraManager
    def get_auras_by_spell_id(self, spell_id) -> list[AppliedAura]:
TypeError: 'type' object is not subscriptable

**Comment by GrenderG** [comment]
You need to use Python 3.9+
