### ISSUE TITLE
COPY failed: forbidden path outside the build context: ../../../../requirements.txt ()

### ISSUE THREAD

**Issue by Firewarrior565** [The-Alpha-Project/alpha-core#1460]
**Describe the bug**
I was building up a Raspberry pi OS (Debian 12 Bookworm) based Alpha server fresh today. I configured things as I did in my video guide and then I ended up getting this at the end when I did docker-compose up -d

Step 4/6 : COPY ../../../../requirements.txt .
COPY failed: forbidden path outside the build context: ../../../../requirements.txt ()
ERROR: Service 'main' failed to build : Build failed

**Steps to reproduce**
1. ...Configure settings.
2. ... Run docker-compose up -d
3. ... See the error

**Expected behavior**
Should build the containers and start them.

**Screenshots**
![alpha_error_1](https://github.com/user-attachments/assets/20d4741d-e70c-47f3-bd8e-b4a0cec861fa)

**Comment by diff3** [comment]
I think I got a fix, I make a push later, but if you want to try it. change. 
COPY ../../../../requirements.txt to COPY requirements.txt in docker-compose.yaml file.

**Comment by Firewarrior565** [comment]
Sorry I've been plaguing it for a few days or I would have tried to tackle it too :)

So running through the steps. 

I edited etc/docker/main/Dockerfile 

From:


RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

WORKDIR /var/wow
COPY ../../../../requirements.txt .
RUN pip3 install -r requirements.txt

ENTRYPOINT ["python3", "main.py"]


To:


RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

WORKDIR /var/wow
COPY requirements.txt .
RUN pip3 install -r requirements.txt

ENTRYPOINT ["python3", "main.py"]


Then I ran:  docker-compose up -d

All appears to be happy now.

**Comment by Firewarrior565** [comment]
Unfortunately, now I'm hitting this when monitoring alpha-core's container starting up. I shut the containers down and rebooted the machine and tried a fresh startup but still the same issue.


[INFO] [18/11/2024 02:43:38] Loading creatures, Map Azeroth, Instance 0... [17919/18862] (95%)
[SUCCESS] [18/11/2024 02:43:38] Loading creatures, Map Azeroth, Instance 0... [18862/18862] (100%)
Process World process:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/var/wow/game/world/WorldManager.py", line 262, in start_world
    WorldLoader.load_data()
  File "/var/wow/game/world/WorldLoader.py", line 109, in load_data
    MapManager.initialize_world_and_pvp_maps()
  File "/var/wow/game/world/managers/maps/MapManager.py", line 54, in initialize_world_and_pvp_maps
    MapManager._build_map(map_id, map_id)
  File "/var/wow/game/world/managers/maps/MapManager.py", line 78, in _build_map
    new_map.initialize()
  File "/var/wow/game/world/managers/maps/Map.py", line 29, in initialize
    self._load_map_creatures()
  File "/var/wow/game/world/managers/maps/Map.py", line 47, in _load_map_creatures
    creature_spawn_instance.spawn()
  File "/var/wow/game/world/managers/objects/units/creature/CreatureSpawn.py", line 111, in spawn
    self.creature_instance = CreatureBuilder.create(creature_template_id, creature_location,
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/wow/game/world/managers/objects/units/creature/CreatureBuilder.py", line 35, in create
    creature_instance = CreatureManager()
                        ^^^^^^^^^^^^^^^^^
  File "/var/wow/game/world/managers/objects/units/creature/CreatureManager.py", line 35, in __init__
    super().__init__(**kwargs)
  File "/var/wow/game/world/managers/objects/units/UnitManager.py", line 101, in __init__
    super().__init__(**kwargs)
  File "/var/wow/game/world/managers/objects/ObjectManager.py", line 67, in __init__
    self.update_packet_factory = UpdatePacketFactory()
                                 ^^^^^^^^^^^^^^^^^^^^^
  File "/var/wow/network/packet/update/UpdatePacketFactory.py", line 26, in __init__
    self.update_mask = UpdateMask()
                       ^^^^^^^^^^^^
  File "/var/wow/network/packet/update/UpdateMask.py", line 13, in __init__
    self.lock = RLock()  # Reentrant lock.
                ^^^^^^^
  File "/usr/local/lib/python3.12/multiprocessing/context.py", line 73, in RLock
    return RLock(ctx=self.get_context())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/multiprocessing/synchronize.py", line 194, in __init__
    SemLock.__init__(self, RECURSIVE_MUTEX, 1, 1, ctx=ctx)
  File "/usr/local/lib/python3.12/multiprocessing/synchronize.py", line 57, in __init__
    sl = self._semlock = _multiprocessing.SemLock(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 24] No file descriptors available

**Comment by GrenderG** [comment]
I think @diff3 also got a fix for that. It's caused by Alpine Linux used by Docker.

**Comment by GrenderG** [comment]
Fixed: https://github.com/The-Alpha-Project/alpha-core/pull/1463
