### ISSUE TITLE
Crash when out of window on kill

### ISSUE THREAD

**Issue by Kyoril** [The-Alpha-Project/alpha-core#15]
I was attacking a target with melee attacks. The client was started with -windowed. When changing to another window just before the target would have died, the server crashed.

I don't know if this is related of if the server just randomly crashed. Here is the server log (windows)

> ←[36m←[1m[DEBUG]←[0m [127.0.0.1] Handling OpCode.CMSG_SET_TARGET
Exception in thread Thread-3700:
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Python39\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Kyoril\Desktop\alpha-core-master\game\world\managers\objects\player\PlayerManager.py", line 883, in update
    self.attack_update(elapsed)
  File "C:\Users\Kyoril\Desktop\alpha-core-master\game\world\managers\objects\player\PlayerManager.py", line 750, in attack_update
    self.update_melee_attacking_state()
  File "C:\Users\Kyoril\Desktop\alpha-core-master\game\world\managers\objects\UnitManager.py", line 296, in update_melee_attacking_state
    self.attacker_state_update(self.combat_target, AttackTypes.BASE_ATTACK, False)
  File "C:\Users\Kyoril\Desktop\alpha-core-master\game\world\managers\objects\UnitManager.py", line 339, in attacker_state_update
    self.send_attack_state_update(damage_info)
  File "C:\Users\Kyoril\Desktop\alpha-core-master\game\world\managers\objects\UnitManager.py", line 405, in send_attack_state_update
    self.deal_damage(damage_info.target, damage_info.total_damage)
  File "C:\Users\Kyoril\Desktop\alpha-core-master\game\world\managers\objects\UnitManager.py", line 436, in deal_damage
    target.die(self)
  File "C:\Users\Kyoril\Desktop\alpha-core-master\game\world\managers\objects\CreatureManager.py", line 230, in die
    self.reward_kill_xp(killer)
  File "C:\Users\Kyoril\Desktop\alpha-core-master\game\world\managers\objects\CreatureManager.py", line 239, in reward_kill_xp
    player.give_xp([Formulas.CreatureFormulas.xp_reward(self.level, player.level, is_elite)], self)
  File "C:\Users\Kyoril\Desktop\alpha-core-master\game\world\managers\objects\player\PlayerManager.py", line 442, in give_xp
    self.mod_level(self.level + 1)
  File "C:\Users\Kyoril\Desktop\alpha-core-master\game\world\managers\objects\player\PlayerManager.py", line 467, in mod_level
    data = pack('<3I',
struct.error: argument out of range
←[36m←[1m[DEBUG]←[0m [127.0.0.1] Handling OpCode.CMSG_ATTACKSWING
←[36m←[1m[DEBUG]←[0m [127.0.0.1] Handling OpCode.CMSG_ATTACKSWING
←[36m←[1m[DEBUG]←[0m [127.0.0.1] Handling OpCode.CMSG_ATTACKSWING
←[36m←[1m[DEBUG]←[0m [127.0.0.1] Handling OpCode.CMSG_ATTACKSWING
←[36m←[1m[DEBUG]←[0m [127.0.0.1] Handling OpCode.CMSG_ATTACKSWING
←[36m←[1m[DEBUG]←[0m [127.0.0.1] Handling OpCode.CMSG_ATTACKSWING
←[36m←[1m[DEBUG]←[0m [127.0.0.1] Handling OpCode.CMSG_ATTACKSWING
←[36m←[1m[DEBUG]←[0m [127.0.0.1] Handling OpCode.CMSG_ATTACKSWING
←[36m←[1m[DEBUG]←[0m [127.0.0.1] Handling OpCode.CMSG_ATTACKSWING
←[36m←[1m[DEBUG]←[0m [127.0.0.1] Handling OpCode.CMSG_ATTACKSWING
←[36m←[1m[DEBUG]←[0m [127.0.0.1] Handling OpCode.CMSG_ATTACKSWING
←[36m←[1m[DEBUG]←[0m [127.0.0.1] Handling OpCode.CMSG_ATTACKSWING
←[36m←[1m[DEBUG]←[0m [127.0.0.1] Handling OpCode.CMSG_ATTACKSWING
←[36m←[1m[DEBUG]←[0m [127.0.0.1] Handling OpCode.CMSG_ATTACKSWING

**Comment by GrenderG** [comment]
Hello! Since the client was in a early state it's really prone to random crashes, seems like it got stuck indeed for some reason and started spamming `CMSG_ATTACKSWING`. I also noticed that the client behaves a bit weirdly sometimes when it's not in foreground.

**Comment by GrenderG** [comment]
Hello! Do you remember the level of your character? Did the client crash or you just got a Disconnected? Thanks a lot.

**Comment by Kyoril** [comment]
Sorry for the late response. It was the latest build from today morning. Interestingly, I neither got a client crash nor a server crash. Although for a while, I could not auto attack any more.

My character was a level 1 or 2 undead in the starting area.

After a while, attacking started working again.

**Comment by GrenderG** [comment]
Were you using any equipment that gave you extra stamina or intellect? Regarding the other issue, I'll take a look, thanks a lot for reporting!

**Comment by Kyoril** [comment]
I was not using any equipment other than the default start equipment. So no extra stats there.
