### ISSUE TITLE
Server crash in destroy_near_object

### ISSUE THREAD

**Issue by X-Genesis-Qhulut** [The-Alpha-Project/alpha-core#466]
**Describe the bug**
During testing of the bug https://github.com/The-Alpha-Project/alpha-core/issues/462 I found the server became unresponsive. Checking its log window I saw the following:

```
Exception in thread Thread-15 (process_incoming):
 Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1776.0_x64__qbz5n2kfra8p0\lib\threading.py", line 1016, in _bootstrap_inner
self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1776.0_x64__qbz5n2kfra8p0\lib\threading.py", line 953, in run
self._target(*self._args, **self._kwargs)
  File "C:\Users\username\Development\alpha-core\game\world\WorldManager.py", line 100, in process_incoming
  File "C:\Users\username\Development\alpha-core\game\world\opcode_handling\handlers\world\WorldTeleportHandler.py", line 28, in handle_ack
world_session.player_mgr.spawn_player_from_teleport()
File "C:\Users\username\Development\alpha-core\game\world\managers\objects\units\player\PlayerManager.py", line 584, in spawn_player_from_teleport
MapManager.update_object(self)
  File "C:\Users\username\Development\alpha-core\game\world\managers\maps\MapManager.py", line 343, in update_object
   grid_manager.update_object(world_object, old_grid_manager, has_changes=has_changes, 
  File "C:\Users\username\Development\alpha-core\game\world\managers\maps\GridManager.py", line 49, in update_object
self.update_players(current_cell_key, exclude_cells=affected_cells)
  File "C:\Users\username\Development\alpha-core\game\world\managers\maps\GridManager.py", line 125, in update_players
cell.update_players(world_object=world_object, has_changes=has_changes, has_inventory_changes=has_inventory_changes)
  File "C:\Users\username\Development\alpha-core\game\world\managers\maps\GridManager.py", line 373, in update_players
    player.update_known_world_objects()
  File "C:\Users\username\Development\alpha-core\game\world\managers\objects\units\player\PlayerManager.py", line 431, in update_known_world_objects
    self.destroy_near_object(guid, skip_check=True)
  File "C:\Users\username\Development\alpha-core\game\world\managers\objects\units\player\PlayerManager.py", line 446, in destroy_near_object
del self.known_objects[guid]
KeyError
```

**Steps to reproduce**
I'm not sure. I have been testing the other bug at some length and this only happened once. Basically I was repeatedly testing the issue 462 when it happened.

**Expected behavior**
That the server not crash with KeyError exception.

**Comment by X-Genesis-Qhulut** [comment]
Regarding the above, the console output I posted above was not exactly what I saw. I cleaned it up a bit to make the Python error easier to read. This is the original:

```
Exception in thread [DEBUG]Thread-15 (process_incoming):
 [12/08/2022 15:40:28] [127.0.0.1] -> Sending  SMSG_DESTROY_OBJECT n=8 0xc6 0xd2 0x0 0x0 0x0 0x0 0x30 0xf1Traceback (most recent call last):

  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1776.0_x64__qbz5n2kfra8p0\lib\threading.py", line 1016, in _bootstrap_inner
[DEBUG] [12/08/2022 15:40:28] [127.0.0.1] -> Sending  SMSG_DESTROY_OBJECT n=8 0xc7 0xd2 0x0 0x0 0x0 0x0 0x30 0xf1
[DEBUG] [12/08/2022 15:40:28] [127.0.0.1] -> Sending  SMSG_DESTROY_OBJECT n=8 0xc8 0xd2 0x0 0x0 0x0 0x0 0x30 0xf1
self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1776.0_x64__qbz5n2kfra8p0\lib\threading.py", line 953, in run
[DEBUG] [12/08/2022 15:40:28] [127.0.0.1] -> Sending  SMSG_DESTROY_OBJECT n=8 0xc9 0xd2 0x0 0x0 0x0 0x0 0x30 0xf1
[DEBUG] [12/08/2022 15:40:28] [127.0.0.1] -> Sending  SMSG_DESTROY_OBJECT n=8 0xca 0xd2 0x0 0x0 0x0 0x0 0x30 0xf1
self._target(*self._args, **self._kwargs)
[DEBUG]  File "C:\Users\username\Development\alpha-core\game\world\WorldManager.py", line 100, in process_incoming
 [12/08/2022 15:40:28] [127.0.0.1] -> Sending  SMSG_DESTROY_OBJECT n=8 0x15 0xd3 0x0 0x0 0x0 0x0 0x30 0xf1
[DEBUG]     [12/08/2022 15:40:28] [127.0.0.1] -> Sending  SMSG_DESTROY_OBJECT n=8 0x1d 0xd3 0x0 0x0 0x0 0x0 0x30 0xf1res = handler(self, self.request, reader)

  File "C:\Users\username\Development\alpha-core\game\world\opcode_handling\handlers\world\WorldTeleportHandler.py", line 28, in handle_ack
[DEBUG] [12/08/2022 15:40:28] [127.0.0.1] -> Sending  SMSG_DESTROY_OBJECT n=8 0x1e 0xd3 0x0 0x0 0x0 0x0 0x30 0xf1
[DEBUG] [12/08/2022 15:40:28] [127.0.0.1] -> Sending  SMSG_DESTROY_OBJECT n=8 0x1f 0xd3 0x0 0x0 0x0 0x0 0x30 0xf1
[DEBUG] [12/08/2022 15:40:28] [127.0.0.1] -> Sending  SMSG_DESTROY_OBJECT n=8 0xae 0x60 0x1 0x0 0x0 0x0 0x30 0xf1
[DEBUG] [12/08/2022 15:40:28] [127.0.0.1] -> Sending  SMSG_DESTROY_OBJECT n=8 0xb3 0x60 0x1 0x0 0x0 0x0 0x30 0xf1
[DEBUG] [12/08/2022 15:40:28] [127.0.0.1] -> Sending  SMSG_DESTROY_OBJECT n=8 0x20 0xd3 0x0 0x0 0x0 0x0 0x30 0xf1
[DEBUG] [12/08/2022 15:40:28] [127.0.0.1] -> Sending  SMSG_DESTROY_OBJECT n=8 0x23 0xd3 0x0 0x0 0x0 0x0 0x30 0xf1
[DEBUG] [12/08/2022 15:40:28] [127.0.0.1] -> Sending  SMSG_DESTROY_OBJECT n=8 0x3e 0xd3 0x0 0x0 0x0 0x0 0x30 0xf1
[DEBUG] [12/08/2022 15:40:28] [127.0.0.1] -> Sending  SMSG_DESTROY_OBJECT n=8 0xa4 0xd4 0x0 0x0 0x0 0x0 0x30 0xf1
[DEBUG] [12/08/2022 15:40:28] [127.0.0.1] -> Sending  SMSG_DESTROY_OBJECT n=8 0xa5 0xd4 0x0 0x0 0x0 0x0 0x30 0xf1
[DEBUG] [12/08/2022 15:40:28] [127.0.0.1] -> Sending  SMSG_DESTROY_OBJECT n=8 0xa6 0xd4 0x0 0x0 0x0 0x0 0x30 0xf1
[DEBUG] [12/08/2022 15:40:28] [127.0.0.1] -> Sending  SMSG_DESTROY_OBJECT n=8 0xa7 0xd4 0x0 0x0 0x0 0x0 0x30 0xf1
[DEBUG] [12/08/2022 15:40:28] [127.0.0.1] -> Sending  SMSG_DESTROY_OBJECT n=8 0xf4 0x60 0x1 0x0 0x0 0x0 0x30 0xf1
[DEBUG] [12/08/2022 15:40:28] [127.0.0.1] -> Sending  SMSG_DESTROY_OBJECT n=8 0x63 0xd2 0x0 0x0 0x0 0x0 0x30 0xf1
[DEBUG] [12/08/2022 15:40:28] [127.0.0.1] -> Sending  SMSG_DESTROY_OBJECT n=8 0x64 0xd2 0x0 0x0 0x0 0x0 0x30 0xf1
[DEBUG] [12/08/2022 15:40:28] [127.0.0.1] -> Sending  SMSG_DESTROY_OBJECT n=8 0x65 0xd2 0x0 0x0 0x0 0x0 0x30 0xf1
[DEBUG] [12/08/2022 15:40:28] [127.0.0.1] -> Sending  SMSG_DESTROY_OBJECT n=8 0xc5 0xd2 0x0 0x0 0x0 0x0 0x30 0xf1
[DEBUG] [12/08/2022 15:40:28] [127.0.0.1] -> Sending  SMSG_DESTROY_OBJECT n=8 0xd5 0x5f 0x1 0x0 0x0 0x0 0x30 0xf1
[DEBUG] [12/08/2022 15:40:28] [127.0.0.1] -> Sending  SMSG_DESTROY_OBJECT n=8 0xda 0x5f 0x1 0x0 0x0 0x0 0x30 0xf1
[DEBUG] [12/08/2022 15:40:28] [127.0.0.1] -> Sending  SMSG_DESTROY_OBJECT n=8 0x66 0xd2 0x0 0x0 0x0 0x0 0x30 0xf1
[DEBUG] [12/08/2022 15:40:28] [127.0.0.1] -> Sending  SMSG_DESTROY_OBJECT n=8 0xde 0x60 0x1 0x0 0x0 0x0 0x30 0xf1
    world_session.player_mgr.spawn_player_from_teleport()
[DEBUG]  File "C:\Users\username\Development\alpha-core\game\world\managers\objects\units\player\PlayerManager.py", line 584, in spawn_player_from_teleport
 [12/08/2022 15:40:28] [127.0.0.1] -> Sending  SMSG_DESTROY_OBJECT n=8 0x68 0x60 0x1 0x0 0x0 0x0 0x30 0xf1
    [DEBUG]MapManager.update_object(self)
  File "C:\Users\username\Development\alpha-core\game\world\managers\maps\MapManager.py", line 343, in update_object
 [12/08/2022 15:40:28] [127.0.0.1] -> Sending  SMSG_DESTROY_OBJECT n=8 0xdd 0x60 0x1 0x0 0x0 0x0 0x30 0xf1
[DEBUG]    grid_manager.update_object(world_object, old_grid_manager, has_changes=has_changes, [12/08/2022 15:40:28] [127.0.0.1] -> Sending  SMSG_DESTROY_OBJECT n=8 0xf 0x61 0x1 0x0 0x0 0x0 0x30 0xf1

  File "C:\Users\username\Development\alpha-core\game\world\managers\maps\GridManager.py", line 49, in update_object
[DEBUG] [12/08/2022 15:40:28] [127.0.0.1] -> Sending  SMSG_DESTROY_OBJECT n=8 0x62 0xd2 0x0 0x0 0x0 0x0 0x30 0xf1
self.update_players(current_cell_key, exclude_cells=affected_cells)[DEBUG]
  File "C:\Users\username\Development\alpha-core\game\world\managers\maps\GridManager.py", line 125, in update_players
 [12/08/2022 15:40:28] [127.0.0.1] -> Sending  SMSG_DESTROY_OBJECT n=8 0x5e 0xd3 0x0 0x0 0x0 0x0 0x30 0xf1
[DEBUG]     [12/08/2022 15:40:28] [127.0.0.1] -> Sending  SMSG_DESTROY_OBJECT n=8 0x5f 0xd3 0x0 0x0 0x0 0x0 0x30 0xf1cell.update_players(world_object=world_object, has_changes=has_changes, has_inventory_changes=has_inventory_changes)

  File "C:\Users\username\Development\alpha-core\game\world\managers\maps\GridManager.py", line 373, in update_players
[DEBUG] [12/08/2022 15:40:28] [127.0.0.1] -> Sending  SMSG_DESTROY_OBJECT n=8 0x6c 0xd3 0x0 0x0 0x0 0x0 0x30 0xf1
    player.update_known_world_objects()[DEBUG]
  File "C:\Users\username\Development\alpha-core\game\world\managers\objects\units\player\PlayerManager.py", line 431, in update_known_world_objects
 [12/08/2022 15:40:28] [127.0.0.1] -> Sending  SMSG_DESTROY_OBJECT n=8 0xef 0x60 0x1 0x0 0x0 0x0 0x30 0xf1
[DEBUG] [12/08/2022 15:40:28] [127.0.0.1] -> Sending  SMSG_DESTROY_OBJECT n=8 0xf6 0x60 0x1 0x0 0x0 0x0 0x30 0xf1
    self.destroy_near_object(guid, skip_check=True)[DEBUG]
  File "C:\Users\username\Development\alpha-core\game\world\managers\objects\units\player\PlayerManager.py", line 446, in destroy_near_object
 [12/08/2022 15:40:28] [127.0.0.1] -> Sending  SMSG_DESTROY_OBJECT n=8 0xb2 0x60 0x1 0x0 0x0 0x0 0x30 0xf1
[DEBUG] [12/08/2022 15:40:28] [127.0.0.1] -> Sending  SMSG_DESTROY_OBJECT n=8 0x9b 0x5f 0x1 0x0 0x0 0x0 0x30 0xf1
del self.known_objects[guid]
KeyError[DEBUG]: 17379390962022792941 [12/08/2022 15:40:28] [127.0.0.1] -> Sending  SMSG_DESTROY_OBJECT n=8 0xd5 0xb1 0x0 0x0 0x0 0x0 0x30 0xf1

[DEBUG] [12/08/2022 15:40:28] [127.0.0.1] -> Sending  SMSG_DESTROY_OBJECT n=8 0x73 0xce 0x0 0x0 0x0 0x0 0x30 0xf1
[DEBUG] [12/08/2022 15:40:28] [127.0.0.1] -> Sending  SMSG_DESTROY_OBJECT n=8 0x91 0xce 0x0 0x0 0x0 0x0 0x30 0xf1
[DEBUG] [12/08/2022 15:40:28] [127.0.0.1] -> Sending  SMSG_DESTROY_OBJECT n=8 0xc3 0x51 0x1 0x0 0x0 0x0 0x30 0xf1
[DEBUG] [12/08/2022 15:40:28] [127.0.0.1] -> Sending  SMSG_DESTROY_OBJECT n=8 0x48 0x5f 0x1 0x0 0x0 0x0 0x30 0xf1
[DEBUG] [12/08/2022 15:40:28] [127.0.0.1] -> Sending  SMSG_DESTROY_OBJECT n=8 0xd8 0x5f 0x1 0x0 0x0 0x0 0x30 0xf1
[DEBUG] [12/08/2022 15:40:28] [127.0.0.1] -> Sending  SMSG_DESTROY_OBJECT n=8 0x6d 0x60 0x1 0x0 0x0 0x0 0x30 0xf1
[DEBUG] [12/08/2022 15:40:28] [127.0.0.1] -> Sending  SMSG_DESTROY_OBJECT n=8 0xbe 0xa6 0x0 0x0 0x0 0x0 0x10 0xf1
[DEBUG] [12/08/2022 15:40:28] [127.0.0.1] -> Sending  SMSG_DESTROY_OBJECT n=8 0xb 0x2b 0x0 0x0 0x0 0x0 0x10 0xf1
[DEBUG] [12/08/2022 15:40:28] [127.0.0.1] -> Sending  SMSG_DESTROY_OBJECT n=8 0x53 0x7e 0x0 0x0 0x0 0x0 0x10 0xf1
[DEBUG] [12/08/2022 15:40:28] [127.0.0.1] -> Sending  SMSG_DESTROY_OBJECT n=8 0xa8 0xc 0x0 0x0 0x0 0x0 0x10 0xf1
[DEBUG] [12/08/2022 15:40:28] [127.0.0.1] -> Sending  SMSG_DESTROY_OBJECT n=8 0xb7 0xe 0x0 0x0 0x0 0x0 0x10 0xf1
[DEBUG] [12/08/2022 15:40:28] [127.0.0.1] -> Sending  SMSG_DESTROY_OBJECT n=8 0xa7 0xa6 0x0 0x0 0x0 0x0 0x10 0xf1
[DEBUG] [12/08/2022 15:40:28] [127.0.0.1] -> Sending  SMSG_DESTROY_OBJECT n=8 0x0 0xa7 0x0 0x0 0x0 0x0 0x10 0xf1
[DEBUG] [12/08/2022 15:40:28] [127.0.0.1] -> Sending  SMSG_DESTROY_OBJECT n=8 0x7 0xa7 0x0 0x0 0x0 0x0 0x10 0xf1
[DEBUG] [12/08/2022 15:40:28] [127.0.0.1] -> Sending  SMSG_DESTROY_OBJECT n=8 0x5d 0x77 0x0 0x0 0x0 0x0 0x10 0xf1
[DEBUG] [12/08/2022 15:40:28] [127.0.0.1] -> Sending  SMSG_DESTROY_OBJECT n=8 0xc7 0x7c 0x0 0x0 0x0 0x0 0x10 0xf1
[DEBUG] [12/08/2022 15:40:28] [127.0.0.1] -> Sending  SMSG_DESTROY_OBJECT n=8 0xb2 0xd 0x0 0x0 0x0 0x0 0x10 0xf1
[DEBUG] [12/08/2022 15:40:28] [127.0.0.1] -> Sending  SMSG_DESTROY_OBJECT n=8 0x6d 0x79 0x0 0x0 0x0 0x0 0x10 0xf1
[DEBUG] [12/08/2022 15:40:28] [127.0.0.1] -> Sending  SMSG_DESTROY_OBJECT n=8 0xa2 0xa6 0x0 0x0 0x0 0x0 0x10 0xf1
```

First, to explain the hex numbers, I modified the server to show when it sent a SMSG_xxxx message, and for debugging another issue I added a display of the first 20 bytes of the payload of the message.

```
[DEBUG] [12/08/2022 15:40:28] [127.0.0.1] -> Sending  SMSG_DESTROY_OBJECT n=8 0xa2 0xa6 0x0 0x0 0x0 0x0 0x10 0xf1
                                                                          ^^^ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                                       length payload
```

I don't think this is causing the issue however. What is clear from the output is that two threads are running at once, with their output interleaved. I notice that each client is given a thread for input and output (network) data, plus various others (I presume for timed events like combat).

I cannot see any calls to threading.Lock() which would be used for preventing race conditions.

---

I strongly suspect that the crash in this report was caused by a race condition - two pieces of code accessing or changing a variable in an unsynchronised way.

See https://realpython.com/intro-to-python-threading/ for a description of race conditions.

Unless this is being handled in a different way that I am unable to see, you will need to prevent race conditions. Crashes like the above will only get worse with more players. Indeed there may be data corruption which is not picked up by Python (unlike the above) which will just result in players getting incorrect results, and possibly corrupt data written back to the database.

Two ways of solving this:

1. Rewrite without using threads. This can be done, but will require quite a bit of work.
 
2. Put locks around handlers.
    * You need a single lock object: `global_lock = threading.Lock()`
    * I suggest the moment a complete CMSG_xxxx arrives that is the time to acquire the lock: 
    ```
    global_lock.acquire()
    res = handler(self, self.request, reader)
    global_lock.release()
    ```
    * Ditto for the handlers for timed events (combat ticks etc.)
    * You may want to put a guard clause (try/except/else) around the handler function call, so that if it crashes the lock is not kept indefinitely.

---

The very nature of race conditions is that they are hard to reproduce, which explains why I only had one such crash during repeated testing of another bug. And they will also probably cause different and annoying bugs which will take a lot of work to find, because you don't normally expect variables to change from one value to another in the middle of code, uncommanded.

**Comment by X-Genesis-Qhulut** [comment]
I see from further investigation that there are locks being taken out using ordinary variables, however as far as I can see these are per session, not global. A global lock might be safer.
